#!/usr/bin/python

import simplejson
import fileinput
import sys

def get_id(value):
    return value["id"]

try:
    line = fileinput.input()[0].rstrip()
    user = simplejson.loads(line)

    with open('users.json', "r") as users_file:
        users = simplejson.load(users_file)
        user_id_max = max(users, key=get_id)
        print(user_id_max)
        new_id = user_id_max["id"] + 1
        user["id"] = new_id
        users.append(user)

    with open('users.json', "w") as users_file:
        simplejson.dump(users, users_file, indent=2)
        print({ "state": "success" })
except Exception, e:
    print simplejson.dumps({'error':"%s"%e})
    sys.exit(1)
