#!/usr/bin/python

import simplejson
import fileinput
import sys

try:
    line = fileinput.input()[0].rstrip()
    input = simplejson.loads(line)

    with open('users.json', "r") as users_file:
        users = simplejson.load(users_file)
        id = input["id"]
        user_to_delete = filter(lambda user: user["id"] == id, users)[0]
        users.remove(user_to_delete)

    with open('users.json', "w") as users_file:
        simplejson.dump(users, users_file, indent=2)
        print({ "state": "success" })
except Exception, e:
    print simplejson.dumps({'error':"%s"%e})
    sys.exit(1)
